import json
import os
import time
import random
import pandas as pd
from curl_cffi import requests
from datetime import datetime

# ডিরেক্টরি সেটআপ
os.makedirs('data', exist_ok=True)
os.makedirs('reports', exist_ok=True)

class WingoEnterprise:
    def __init__(self):
        self.url = "https://draw.ar-lottery01.com/WinGo/WinGo_30S/GetHistoryIssuePage.json"
        self.file_path = "data/wingo_master_history.json"
        # বিভিন্ন ব্রাউজার প্রোফাইল থেকে র‍্যান্ডম চয়েস (বট ডিটেকশন এড়াতে)
        self.impersonates = ["chrome110", "chrome120", "edge101", "safari_ios_16_0"]

    def get_dynamic_headers(self):
        return {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=UTF-8",
            "User-Agent": f"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{random.randint(110, 122)}.0.0.0 Safari/537.36",
            "X-Requested-With": "XMLHttpRequest",
            "Origin": "https://draw.ar-lottery01.com",
            "Referer": "https://draw.ar-lottery01.com/"
        }

    def fetch_data(self):
        payload = {"pageIndex": 1, "pageSize": 50, "type": 30}
        
        try:
            # সেশন ব্যবহার করে কুকি হ্যান্ডেল করা
            with requests.Session() as s:
                response = s.post(
                    self.url,
                    json=payload,
                    headers=self.get_dynamic_headers(),
                    impersonate=random.choice(self.impersonates),
                    timeout=30
                )
            
            if response.status_code == 200:
                raw_res = response.json()
                if 'data' in raw_res:
                    return raw_res['data']['list']
            print(f"Warning: Status Code {response.status_code}")
            return None
        except Exception as e:
            print(f"Critical Error: {e}")
            return None

    def process_and_analyze(self, new_data):
        if not new_data: return

        # লোড বর্তমান ডাটা
        history = []
        if os.path.exists(self.file_path):
            with open(self.file_path, "r") as f:
                history = json.load(f)

        # নতুন ডাটা মার্জ করা
        existing_ids = {str(x['issueNumber']) for x in history}
        updated = False
        for item in new_data:
            if str(item['issueNumber']) not in existing_ids:
                history.append(item)
                updated = True

        if not updated:
            print("No new trends found.")
            return

        # সর্টিং (লেটেস্ট ডাটা আগে)
        history = sorted(history, key=lambda x: str(x['issueNumber']), reverse=True)[:20000]

        with open(self.file_path, "w") as f:
            json.dump(history, f, indent=2)

        self.generate_market_report(history)

    def generate_market_report(self, history):
        """ডাটা থেকে মার্কেট ট্রেন্ড অ্যানালাইসিস করা"""
        df = pd.DataFrame(history)
        
        # লেটেস্ট ১০টি ড্র-এর ট্রেন্ড
        latest_results = df.head(10)[['issueNumber', 'number', 'colour']].to_markdown()
        
        # কালার ফ্রিকোয়েন্সি
        color_counts = df.head(100)['colour'].value_counts().to_dict()
        
        report = f"""
# 📊 Wingo Enterprise Market Intelligence Report
**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

### 🚀 Recent Draw History (Top 10)
{latest_results}

### 📈 Probability Analysis (Last 100 Draws)
- **Red:** {color_counts.get('red', 0)}%
- **Green:** {color_counts.get('green', 0)}%
- **Violet:** {color_counts.get('violet', 0)}%

---
*Generated by Wingo-AI-Bot (v2.0)*
        """
        with open("reports/market_summary.md", "w") as f:
            f.write(report)
        print("Report Generated Successfully.")

if __name__ == "__main__":
    bot = WingoEnterprise()
    # স্মার্ট ওয়েট
    time.sleep(random.uniform(2.5, 7.5))
    data = bot.fetch_data()
    bot.process_and_analyze(data)
                
